apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-service
spec:
  selector:
    app: mongo-express
  typ: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      # nodeport has a range between 30000 -32767
      nodePort: 31111